require 'benchmark'
require 'active_support/json'

class Foo
  def initialize(foo, bar, baz)
    self.foo = foo
    self.bar = bar
    self.baz = baz
  end
  attr_accessor :foo, :bar, :baz
end

object = Foo.new(
  Foo.new(
    Foo.new(
      Foo.new(
        Foo.new(
          Foo.new(
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
          ),
          Foo.new(
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
          ),
          Foo.new(
            Foo.new(
              Foo.new(
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
              ),
              Foo.new(
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
              ),
              Foo.new(
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
              ),
            ),
            Foo.new(
              Foo.new(
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
              ),
              Foo.new(
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
              ),
              Foo.new(
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  nil,
                  nil,
                  nil,
                ),
                Foo.new(
                  Foo.new(
                    Foo.new(
                      nil,
                      nil,
                      nil,
                    ),
                    Foo.new(
                      nil,
                      nil,
                      nil,
                    ),
                    Foo.new(
                      nil,
                      nil,
                      nil,
                    ),
                  ),
                  Foo.new(
                    Foo.new(
                      nil,
                      nil,
                      nil,
                    ),
                    Foo.new(
                      nil,
                      nil,
                      nil,
                    ),
                    Foo.new(
                      Foo.new(
                        Foo.new(
                          nil,
                          nil,
                          nil,
                        ),
                        Foo.new(
                          nil,
                          nil,
                          nil,
                        ),
                        Foo.new(
                          Foo.new(
                            Foo.new(
                              Foo.new(
                                Foo.new(
                                  Foo.new(
                                    Foo.new(
                                      Foo.new(
                                        Foo.new(
                                          Foo.new(
                                            Foo.new(
                                              Foo.new(
                                                Foo.new(
                                                  Foo.new(
                                                    Foo.new(
                                                      Foo.new(
                                                        Foo.new(
                                                          nil,
                                                          nil,
                                                          nil,
                                                        ),
                                                        Foo.new(
                                                          nil,
                                                          nil,
                                                          nil,
                                                        ),
                                                        Foo.new(
                                                          nil,
                                                          nil,
                                                          nil,
                                                        ),
                                                      ),
                                                      nil,
                                                      nil,
                                                    ),
                                                    Foo.new(
                                                      nil,
                                                      nil,
                                                      nil,
                                                    ),
                                                    Foo.new(
                                                      nil,
                                                      nil,
                                                      nil,
                                                    ),
                                                  ),
                                                  nil,
                                                  nil,
                                                ),
                                                Foo.new(
                                                  nil,
                                                  nil,
                                                  nil,
                                                ),
                                                Foo.new(
                                                  nil,
                                                  nil,
                                                  nil,
                                                ),
                                              ),
                                              nil,
                                              nil,
                                            ),
                                            Foo.new(
                                              nil,
                                              nil,
                                              nil,
                                            ),
                                            Foo.new(
                                              nil,
                                              nil,
                                              nil,
                                            ),
                                          ),
                                          nil,
                                          nil,
                                        ),
                                        Foo.new(
                                          nil,
                                          nil,
                                          nil,
                                        ),
                                        Foo.new(
                                          nil,
                                          nil,
                                          nil,
                                        ),
                                      ),
                                      nil,
                                      nil,
                                    ),
                                    Foo.new(
                                      nil,
                                      nil,
                                      nil,
                                    ),
                                    Foo.new(
                                      nil,
                                      nil,
                                      nil,
                                    ),
                                  ),
                                  nil,
                                  nil,
                                ),
                                Foo.new(
                                  nil,
                                  nil,
                                  nil,
                                ),
                                Foo.new(
                                  nil,
                                  nil,
                                  nil,
                                ),
                              ),
                              nil,
                              nil,
                            ),
                            Foo.new(
                              nil,
                              nil,
                              nil,
                            ),
                            Foo.new(
                              nil,
                              nil,
                              nil,
                            ),
                          ),
                          nil,
                          nil,
                        ),
                      ),
                      nil,
                      nil,
                    ),
                  ),
                  nil,
                ),
              ),
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
          ),
        ),
        Foo.new(
          Foo.new(
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
          ),
          Foo.new(
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
            Foo.new(
              nil,
              nil,
              nil,
            ),
          ),
          nil,
        ),
        Foo.new(
          nil,
          nil,
          nil,
        ),
      ),
      Foo.new(
        Foo.new(
          nil,
          nil,
          nil,
        ),
        Foo.new(
          nil,
          nil,
          nil,
        ),
        Foo.new(
          nil,
          nil,
          nil,
        ),
      ),
      Foo.new(
        Foo.new(
          nil,
          nil,
          nil,
        ),
        Foo.new(
          nil,
          nil,
          nil,
        ),
        Foo.new(
          nil,
          nil,
          nil,
        ),
      ),
    ),
    Foo.new(
      nil,
      nil,
      nil,
    ),
    Foo.new(
      nil,
      nil,
      nil,
    ),
  ),
  Foo.new(
    nil,
    nil,
    nil,
  ),
  Foo.new(
    nil,
    nil,
    Foo.new(
      Foo.new(
        nil,
        nil,
        nil,
      ),
      Foo.new(
        nil,
        nil,
        nil,
      ),
      Foo.new(
        nil,
        nil,
        Foo.new(
          Foo.new(
            nil,
            nil,
            nil,
          ),
          Foo.new(
            nil,
            nil,
            nil,
          ),
          Foo.new(
            nil,
            nil,
            Foo.new(
              Foo.new(
                nil,
                nil,
                nil,
              ),
              Foo.new(
                nil,
                nil,
                nil,
              ),
              Foo.new(
                nil,
                nil,
                nil,
              ),
            ),
          ),
        ),
      ),
    ),
  ),
)

puts Benchmark.measure { 50000.times { object.as_json } }
#require 'pp'
#pp object.as_json
