name: test
on:
- push
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - '2.7'
        - '3.0'
        gemfile:
        - v7.gemfile
        - implicitconv.gemfile
        num:
        - 1
        - 2
        - 3
        - 4

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - run: bundle install --gemfile=${{ matrix.gemfile }}
    - run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec ruby bm.rb
    - run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec ruby bm.rb
    - run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec ruby bm.rb
    - run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec ruby bm.rb
